export const guestTables = {
  A: [
    {
      id: '1',
      name: 'Арсенал',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 4,
      draws: 1,
      loses: 1,
      scored: 16,
      conceded: 4,
      points: 13,
      form: ['W', 'W', 'W', 'D', 'D'],
      group: 'B'
    },
    {
      id: '2',
      name: 'ПСВ Эйндховен',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 2,
      draws: 3,
      loses: 1,
      scored: 8,
      conceded: 10,
      points: 9,
      form: ['W', 'L', 'W', 'D', 'L'],
      group: 'B'
    },
    {
      id: '3',
      name: 'Ланс',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 2,
      draws: 2,
      loses: 2,
      scored: 6,
      conceded: 11,
      points: 8,
      form: ['L', 'L', 'W', 'D', 'W'],
      group: 'B'
    },
    {
      id: '4',
      name: 'Севилья',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 0,
      draws: 2,
      loses: 4,
      scored: 7,
      conceded: 12,
      points: 2,
      form: ['L', 'W', 'L', 'L', 'W'],
      group: 'B'
    }
  ],
  B: [
    {
      id: '1',
      name: 'Реал Мадрид',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 6,
      draws: 0,
      loses: 0,
      scored: 16,
      conceded: 7,
      points: 18,
      form: ['W', 'L', 'W', 'W', 'W'],
      group: 'C'
    },
    {
      id: '2',
      name: 'Наполи',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 3,
      draws: 1,
      loses: 2,
      scored: 10,
      conceded: 9,
      points: 10,
      form: ['L', 'W', 'W', 'D', 'L'],
      group: 'C'
    },
    {
      id: '3',
      name: 'Брага',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 2,
      draws: 2,
      loses: 2,
      scored: 6,
      conceded: 11,
      points: 8,
      form: ['W', 'L', 'W', 'D', 'D'],
      group: 'C'
    },
    {
      id: '4',
      name: 'Унион Берлин',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 0,
      draws: 2,
      loses: 4,
      scored: 6,
      conceded: 10,
      points: 2,
      form: ['W', 'D', 'L', 'L', 'D'],
      group: 'C'
    }
  ],
  C: [
    {
      id: '1',
      name: 'Бавария',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 4,
      draws: 1,
      loses: 1,
      scored: 16,
      conceded: 4,
      points: 13,
      form: ['W', 'W', 'W', 'D', 'L'],
      group: 'A'
    },
    {
      id: '2',
      name: 'Копенгаген',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 2,
      draws: 3,
      loses: 1,
      scored: 8,
      conceded: 10,
      points: 9,
      form: ['W', 'W', 'L', 'L', 'W'],
      group: 'A'
    },
    {
      id: '3',
      name: 'Галатасарай',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 2,
      draws: 2,
      loses: 2,
      scored: 6,
      conceded: 11,
      points: 8,
      form: ['L', 'W', 'W', 'W', 'W'],
      group: 'A'
    },
    {
      id: '4',
      name: 'Манчестер Юнайтед',
      logo: 'https://upload.wikimedia.org/wikipedia/ru/thumb/2/24/FC_Barcelona.svg/213px-FC_Barcelona.svg.png',
      games: 6,
      wins: 0,
      draws: 2,
      loses: 4,
      scored: 7,
      conceded: 12,
      points: 2,
      form: ['L', 'D', 'W', 'D', 'D'],
      group: 'A'
    }
  ]
};
